version: '3.7'
run: when_changed

tasks:
  generate-hash:
    - rm -f hash.txt
    - task: input-content
      vars: { CONTENT: '1' }
    - task: input-content
      vars: { CONTENT: '2' }
    - task: input-content
      vars: { CONTENT: '2' }

  input-content:
    deps:
      - task: create-output
        vars: { CONTENT: '1' }
    cmds:
      - echo {{.CONTENT}} >> hash.txt

  create-output:
    run: once
    cmds:
      - echo starting {{.CONTENT}} >> hash.txt

  maybe-happy:
    vars:
      SMILE: ':\)'
      FROWN: ':\('
      HAPPY: true
      NUMBERS2: '0,1,1,1,2,2,3'
      NUMBERS: [0, 1, 1, 1, 2, 2, 3]
    cmds:
      - 'echo {{if .HAPPY}}{{.SMILE}}{{else}}{{.FROWN}}{{end}}'
      - 'echo {{splitList "," .NUMBERS2 | uniq | join ", " }}!'
      - "{{range $index, $num := .NUMBERS}}{{if gt $num 1 }}{{break}}{{end}}echo {{$index}}: {{$num}}\n{{end}}"
